apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-readonly
rules:
- apiGroups: [""]
  resources:
  - nodes
  - pods
  - namespaces
  - services
  - endpoints
  verbs: ["get","list","watch"]

- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  verbs: ["get","list","watch"]

- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["get","list","watch"]
